name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Run some Laravel stuff
      run: |
        php -r "file_exists('.env') || copy('.env.testing', '.env');"
        composer install
        php artisan key:generate
        php artisan migrate
        vendor/bin/phpunit
